import os

BOT_TOKEN = os.environ["BOT_TOKEN"]
ADMIN_ID = int(os.environ["ADMIN_ID"])

CURRENCY = "₹"

MAX_SEND = 5000
MAX_WITHDRAW = 5000

SEND_DAILY_LIMIT = 10000
WITHDRAW_DAILY_LIMIT = 10000

SEND_FEE_PERCENT = 0
WITHDRAW_FEE_PERCENT = 0
